### ISSUE TITLE
Bulk editing

### ISSUE THREAD

**Issue by hooverlunch** [ixti/redmine_tags#122]
Love this plugin! 

It would be so much better with bulk tag editing. i.e. select a bunch of issues, right click, click edit, then there is a box called 'Tags' showing the union of all the tags in the issue set. Any deletions  and additions are applied to the whole set.

Any plans for this? How difficult would it be? Perhaps we will contribute it...

**Comment by PowerKiKi** [comment]
There is an old and long discussion about that over there #57. The bottom line was that there are three options:

1. prevent bulk editing
2. work on intersection (only tags that are present in all selected issues)
3. work on union, and somehow build a "complex" GUI that could manage cases where one tag appears only in one issue

While solution 3 would be the most powerful for end-user it could end up being a lot of work to build and quite complex to use. I believe solution 2 is more modest while still being useful in many cases. However back then nobody had time to do either solution, so we just went with disabling bulk edition.

IMHO if you are willing to implement solution 2 that would already be a very nice contribution.

**Comment by ilpssun** [comment]
For me, it would be a great help to be able to add or delete a single tag to/from a group of tickets.  I don’t think I would need any other type of bulk editing.  For other users, this might also apply to news and wiki pages.  However, I don’t think it’s necessary to have a complex gui to add or remove more than one tag.  That might be the ideal solution but – as I said – I suspect the main use-case is to add/delete a single tag.

**Comment by hooverlunch** [comment]
Yup. Still hoping to get to this someday... :o

**Comment by marius-balteanu** [comment]
Implemented in PR #163 

@PowerKiKi, @hooverlunch,  @ilpssun, it'll be very useful if you have the time to test the implementation and tell me what do you think. I'm planning to release the 3.2.0 version of the plugin this week.

**Comment by hooverlunch** [comment]
Cool! Are you saying we should wait until the version deploys to test, or somehow before then?

**Comment by marius-balteanu** [comment]
No, I just want to get some feedback before the release. If you have any test instance, you can deploy the branch rm_3.4.0 and tell me what you think.

**Comment by PowerKiKi** [comment]
I tested redmine_tags 206793fd690a5910b9d5d3127aa1786a5139b89c on Redmine master branch (1b0206ed). To me, it looks like we are back to what is originally described in #57. Meaning that it is way too easy to lose existing tags.

Firstly because only union of tags are shown, the non-common tags can be lost even though the user don't edit the tags field but an entirely unrelated field. So just adding a note on several issues at a time "force" them to all have the exact same tags.

And then even we want to actually edit tags, showing only the union, but modifying the entire set, makes it very easy for an end-user not to realize that he is going to remove some tags that are not shown.

This situation is exactly why bulk editing was disabled the first time. So I am not in favor of merging this as is.

Like I [explained earlier](https://github.com/ixti/redmine_tags/issues/122#issuecomment-170183943), if we really need bulk editing, then the minimum is to show only unions and modify only unions, never removing non-shown tags.

**Comment by marius-balteanu** [comment]
Thanks for your feedback. Something is wrong, I'll test again today the implementation because it shouldn't work on this way. 

I read the initial problem and choose to implement the following mechanism:
1. show only common tags in bulk edit form
2. if a tag is removed/added, remove/add only the respective tag from the issues
3. if all common tags are removed from the input, remove all common tags from the issues.
4. if the "Clear" option is checked, clear all tags (not only the common) from the tags.

**Comment by PowerKiKi** [comment]
What you describe sounds good. But it's not what I saw. I think you'll be able to reproduce easily since I was on a brand new Redmine install, but if you cannot for some reason, let me know and I'll dig deeper...

**Comment by marius-balteanu** [comment]
I was able to reproduce earlier on my instance.  I'll let you know when I have an working version.

**Comment by marius-balteanu** [comment]
I think we're ready to merge the rm_3.4.0 branch into master. Bulk edit works now as expected with only one mention: I've disabled the clear checkbox (point 4 from my previous comment) because there are some issues with the tagit js library. I'm going to readd the option after we change the library. 

Also, now we have some tests for this feature.

**Comment by PowerKiKi** [comment]
Didn't test, but sounds good to me.

On a side note, I was wondering if the term "clear" was clear enough for the end user. I would have almost suggested something along the line of "remove all be tags". But since it disappeared, it doesn't really matter anymore ;-)

**Comment by marius-balteanu** [comment]
Implemented in version 3.2.0

**Comment by hooverlunch** [comment]
Hooray! Thanks so much for this feature. Going to be very useful for us!
