### ISSUE TITLE
context_menu - (wrong number of arguments (1 for 0))

### ISSUE THREAD

**Issue by winflo** [ixti/redmine_tags#153]
Since https://github.com/redmine/redmine/commit/18073c971e69fcfbfcafc8f2ec81768ea18220f8 the url-param from _context_menu_ was ditched.

This results in an ActionView::Template::Error while rendering the _tags/_manage.html.erb_ page.

**Comment by sdwolf** [comment]
From what I understand, the context menu functionality is now added as a form that wraps tables. This is bad for the settings menu since this implies we will have the context menu form wrapping the tag table, all INSIDE the settings form, which is not valid HTML.

A quick fix would be just to remove the context menu from the "manage tags" section. It is not really that useful since the edit and delete buttons are already present on the row.

/cc @winflo @ixti @PowerKiKi @marius-balteanu let me know what you think.

**Comment by PowerKiKi** [comment]
I don't mind if it's removed. It doesn't bring anything new anyway.

**Comment by winflo** [comment]
In my case, i removed the context_menu from the manage-page as well.

**Comment by ixti** [comment]
@sdwolf 👍
