### ISSUE TITLE
4.1 ?

### ISSUE THREAD

**Issue by ashrafalzyoud** [ixti/redmine_tags#219]
its not support

**Comment by PowerKiKi** [comment]
I've been running this plugin on Redmine 4.1 for months without any problems. If you saw errors, please describe them.

**Comment by ashrafalzyoud** [comment]
Not work with pivot table plugin

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ixti** [comment]
@ashrafalzyoud if you want a help, please help us better understand details:

- What exactly isn't working?
- What errors do you see?
- What plugins (with versions) are you using?

Please, provide error logs if any or screenshots if you think they will help us better understand. Describe your expected behaviour, and behaviour you actually experience.
